# generated by datamodel-codegen:
#   filename:  address_schema.json
#   timestamp: 2025-07-16T02:15:32+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field
from pydantic_partial import create_partial_model


class Address(BaseModel):
    street: str = Field(..., title='Street')
    city: str = Field(..., title='City')
    zip_code: str = Field(..., title='Zip Code')
    country: Optional[str] = Field(None, title='Country')

PartialAddress = create_partial_model(Address, recursive=True)
