# generated by datamodel-codegen:
#   filename:  contact_schema.json
#   timestamp: 2025-07-14T20:37:45+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field
from pydantic_partial import create_partial_model


class Contact(BaseModel):
    phone: str = Field(..., title='Phone')
    email: Optional[str] = Field(None, title='Email')

PartialContact = create_partial_model(Contact, recursive=True)
