# generated by datamodel-codegen:
#   filename:  user_schema.json
#   timestamp: 2025-07-14T20:37:50+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field
from pydantic_partial import create_partial_model


class Address(BaseModel):
    street: str = Field(..., title='Street')
    city: str = Field(..., title='City')
    zip_code: str = Field(..., title='Zip Code')
    country: Optional[str] = Field(None, title='Country')


class Contact(BaseModel):
    phone: str = Field(..., title='Phone')
    email: Optional[str] = Field(None, title='Email')


class User(BaseModel):
    name: str = Field(..., title='Name')
    age: int = Field(..., title='Age')
    address: Address
    contacts: List[Contact] = Field(..., title='Contacts')

PartialAddress = create_partial_model(Address, recursive=True)

PartialContact = create_partial_model(Contact, recursive=True)

PartialUser = create_partial_model(User, recursive=True)
